#MPlayer CE GameCube - samba shares on psOne (10.0.0.99), guest access
#Max 5 shares. Empty ip or share = disabled. Quote names with spaces.

#smb1:/
ip1=10.0.0.99
share1=Movies
user1=
pass1=

#smb2:/
ip2=10.0.0.99
share2=TV
user2=
pass2=

#smb3:/
ip3=10.0.0.99
share3="Anime TV"
user3=
pass3=

#smb4:/
ip4=10.0.0.99
share4="Anime Movie"
user4=
pass4=

#smb5:/
ip5=10.0.0.99
share5=Music
user5=
pass5=
